[window]
decorations = "none"

[colors.primary]
background = "#050A12"
foreground = "#E6FAFF"

[colors.cursor]
text = "#050A12"
cursor = "#00C8FF"

[colors.selection]
text = "#050A12"
background = "#00C8FF"

[colors.normal]
black = "#050A12"
red = "#00A6C7"
green = "#8FEFFF"
yellow = "#B8F5FF"
blue = "#4CCFFF"
magenta = "#78DFFF"
cyan = "#00C8FF"
white = "#E6FAFF"

[colors.bright]
black = "#2A4A5C"
red = "#00E5FF"
green = "#B8F5FF"
yellow = "#E6FAFF"
blue = "#9AF2FF"
magenta = "#A8EFFF"
cyan = "#9AF2FF"
white = "#FFFFFF"
