accent = "#00C8FF"
cursor = "#00C8FF"
foreground = "#D9F7FF"
background = "#050A12"
selection_foreground = "#050A12"
selection_background = "#00C8FF"
color0 = "#050A12"
color1 = "#0B5C7A"
color2 = "#00A6C7"
color3 = "#7FEAFF"
color4 = "#176B89"
color5 = "#406A86"
color6 = "#00C8FF"
color7 = "#D9F7FF"
color8 = "#122738"
color9 = "#00E5FF"
color10 = "#20D9E8"
color11 = "#B8F5FF"
color12 = "#4CCFFF"
color13 = "#6E9FC0"
color14 = "#9AF2FF"
color15 = "#FFFFFF"
