background = #050A12
foreground = #E6FAFF
cursor-color = #00C8FF
selection-background = #00C8FF
selection-foreground = #050A12
palette = 0=#050A12
palette = 1=#00A6C7
palette = 2=#8FEFFF
palette = 3=#B8F5FF
palette = 4=#4CCFFF
palette = 5=#78DFFF
palette = 6=#00C8FF
palette = 7=#E6FAFF
palette = 8=#2A4A5C
palette = 9=#00E5FF
palette = 10=#B8F5FF
palette = 11=#E6FAFF
palette = 12=#9AF2FF
palette = 13=#A8EFFF
palette = 14=#9AF2FF
palette = 15=#FFFFFF
